tfl_realtime:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Local path to the DuckDB file. Use a workspace-relative path so dbt works outside containers.
      path: ../data/silver/tfl.duckdb
      threads: 4
      extensions: [httpfs, parquet]
